### ISSUE TITLE
kubedex-exporter chart removal

### ISSUE THREAD

**Issue by nealf** [Kubedex/charts#3]
Was the removal of the kubedex-exporter chart in recent commits intentional? 

I was able to take the chart from an old commit and convert it into a simple deployment, but was just curious whether its removal had been intentional. Thanks for creating it!

**Comment by sacreman** [comment]
Hi @nealf, apologies, I honestly didn't think anyone was using it.

There is a better chart here: https://github.com/helm/charts/tree/master/stable/helm-exporter

I updated the blog a while ago with a quick note to say the other project is better: https://kubedex.com/kubedex-helm-chart-exporter-for-prometheus/

If you'd like to still use the Kubedex one I can put it back into the repo but I think it's worse in almost every way to the one @sstarcher created.

**Comment by nealf** [comment]
No worries, I figured something like that might be the case, and I must have missed the update on the blog. I'll check the new one out. Thanks again!

**Comment by sstarcher** [comment]
@sacreman thanks for the compliment and the idea
